### ISSUE TITLE
Feature: expose editor as prop

### ISSUE THREAD

**Issue by jfdelarosa** [TGlide/novel-svelte#3]
It would be useful to expose the tiptap editor instance as a prop, that way we can execute commands programmatically, for example:

```
<script>
import { Editor } from 'novel-svelte';

let editor;
</script>

<button on:click={() => { editor.commands.setBold() }}>bold</button>
<Editor bind:editor>
```

**Comment by rotimi-best** [comment]
Completely agree with this. Would love to have this as well.

**Comment by rotimi-best** [comment]
This issue has been fixed here: https://github.com/TGlide/novel-svelte/pull/11

Thanks @TGlide
